### ISSUE TITLE
Logos for data providers need to be on each state profile

### ISSUE THREAD

**Issue by timathomas** [evictionresearch/evictionresearch.github.io#27]

**Comment by timathomas** [comment]
@JuliaGreenberg1 just want to double check. Oregon was missing it.

**Comment by JuliaGreenberg1** [comment]
@timathomas Sounds good - will keep this in mind for future profiles!

**Comment by timathomas** [comment]
IN, MN, and DE are missing logos too.

**Comment by JuliaGreenberg1** [comment]
Ah right, this must have disappeared when we switched from the Rmd to HTML. Do you know how to add a logo to the HTML?
